pages/blocks/header/header.js
pages/scripts/scripts.js
pages/themes/story.css

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/
- After: https://story--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/

refactor: rename template genesis > story

---

pages/blocks/reveal/reveal.css
pages/blocks/reveal/reveal.js
pages/scripts/scripts.js

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/
- After: https://story--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/arnoldpalmerinvitational/
- After: https://story--pgatour-com--hlxsites.hlx.page/pages/arnoldpalmerinvitational/

fix: Story bugs

---

pages/blocks/reveal/reveal.css
pages/blocks/reveal/reveal.js

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/arnoldpalmerinvitational/placement-test
- After: https://story--pgatour-com--hlxsites.hlx.page/pages/arnoldpalmerinvitational/placement-test

feat: focusing media position

---

pages/blocks/reveal/reveal.css
pages/blocks/reveal/reveal.js

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/drafts/SeanMartin/riviera-test
- After: https://story--pgatour-com--hlxsites.hlx.page/drafts/SeanMartin/riviera-test

fix: landscape v. portrait videos

---

pages/blocks/reveal/reveal.css
pages/blocks/reveal/reveal.js

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/
- After: https://story--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/

fix: reveal loading and scroll improvements

---

pages/themes/story.css

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/
- After: https://story--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/

fix: adjust default story styles

---

pages/scripts/delayed.js

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational/
- After: https://new-launch-lib--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational/

updated to use same launch lib as pgatour.com

---

pages/scripts/delayed.js

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational/
- After: https://datalayer--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational/

chore: data layer for pgatour.com pages

---

pages/scripts/delayed.js

Before: https://main--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational/
After: https://datalayer--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational/

change how OT events are populated in DL to match pgatour.com

---

pages/scripts/delayed.js

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational/
- After: https://dl-gigya--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational/

integrate gigya info to datalayer

---

pages/blocks/table/table.css
pages/blocks/table/table.js
pages/styles/styles.css

Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/players/international
- After: https://table--pgatour-com--hlxsites.hlx.page/pages/players/international

feat: table and media headline

---

pages/scripts/delayed.js

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.live/pages/arnoldpalmerinvitational/
- After: https://analytics-change--pgatour-com--hlxsites.hlx.live/pages/arnoldpalmerinvitational/

skip block quote blocks from analytics per convo with BVA

---

pages/scripts/scripts.js
pages/themes/info.css

Fix #33
https://github.com/hlxsites/pga-tour-issues/issues/33
Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/golftv/
- After: https://33--golf-tv-page-issues-with-links--pgatour-com--hlxsites.hlx.page/pages/golftv/

Resolved issue with links disappearing from Hero in mobile view

---

pages/themes/story.css

new variant for text on a dark bg in story hero
Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/rahm-scheffler-the-race-for-the-fedexcup/
- After: https://dark-hero-variant--pgatour-com--hlxsites.hlx.page/pages/rahm-scheffler-the-race-for-the-fedexcup/

feat: dark variant on story hero

---

pages/blocks/video/video.css
pages/blocks/video/video.js

When selecting play on a video block with picture, the placeholder image is removed and a video of different height is added. This creates a jump as the HTML is removed an added.
Fix : https://pgatour.atlassian.net/browse/AEMFDEV-89
Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/pages/whats-new
- After: https://aemfdev-89--video-block-issue--pgatour-com--hlxsites.hlx.page/pages/whats-new

Video Block Placeholder Issue

---

pages/blocks/footer/footer.css
pages/blocks/footer/footer.js
pages/scripts/scripts.js

[https://pgatour.atlassian.net/browse/AEMFDEV-153](url)
-Created a function where divs where being used in the markup innerHTML and converted them to the proper ul and li's.
-Added distinct class names to ensure grid layout to match pga-tours web team. 
-added styling and positioning for "Quick Links" to match pga-tour web's footer. 
Test URLs:
- Before: https://main--pgatour-com--hlxsites.hlx.page/
- After: https://footer--pgatour-com--hlxsites.hlx.page/

-Footer matching PGA-TOUR Web Footer

---

pages/blocks/header/header.css
pages/blocks/header/header.js
pages/blocks/hero/hero.css
pages/blocks/hero/hero.js
pages/blocks/reveal/reveal.css
pages/themes/story.css

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
[Fix #<gh-issue-id>](https://pgatour.atlassian.net/browse/TDW-1992)
Test URLs:
Before: https://main--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/
After: https://TDW-1992-story-refresh--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/

TDW-1992 Story Refresh

---

404.html

https://pgatour.atlassian.net/browse/TDW-1992
Test URLs:
Before: https://main--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational
After: https://TDW-1992-story-refresh--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational

TDW-1992 404 Fix

---

pages/blocks/hero/hero.css
pages/themes/story.css

https://pgatour.atlassian.net/browse/TDW-1992
Test URLs:
Before: https://main--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational
After: https://TDW-1992-story-refresh--pgatour-com--hlxsites.hlx.live/pages/genesisinvitational

TDW-1992 Hero Fix

---

package-lock.json
package.json
pages/blocks/reveal/reveal.css
pages/blocks/reveal/reveal.js
pages/icons/volume-off.svg
pages/icons/volume-on.svg
pages/themes/story.css

https://pgatour.atlassian.net/browse/TDW-1982
Test URLs:
https://TDW-1982-Reveal-Refresh--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/test
reveal blocks are added at the end of the test page.

TDW-1982 Reveal block support brightcove and unmute video

---

pages/blocks/reveal/reveal.js
pages/scripts/scripts.js

https://pgatour.atlassian.net/browse/TDW-1982
Test URLs:
https://TDW-1982-Reveal-Refresh--pgatour-com--hlxsites.hlx.page/pages/genesisinvitational/test
reveal blocks are added at the end of the test page.

TDW-1982 reveal refresh

---

pages/scripts/delayed.js
pages/scripts/scripts.js

https://pgatour.atlassian.net/browse/TDW-2161
Test URLs:
https://tdw-2161-enable-gtm--pgatour-com--hlxsites.hlx.page/

TDW-2161 Enable GTM and remove adobe script

---

pages/blocks/reveal/reveal.js
pages/scripts/scripts.js

https://pgatour.atlassian.net/browse/TDW-2233
Test URLs:
https://tdw-2233-reveal-block--pgatour-com--hlxsites.hlx.live/

fix: [TDW-2233] Reveal Block Author Control

---

pages/scripts/scripts.js

https://pgatour.atlassian.net/browse/TDW-2233
Test URLs:
https://move-styles-json--pgatour-com--hlxsites.hlx.live/

fix: [TDW-2233] Moving Styles File and Error Handling
